---
- name: Remove deprecated or insecure packages | package-01 - package-09
  ansible.builtin.apt:
    name: "{{ os_security_packages_list }}"
    state: absent
    purge: true
  when: os_security_packages_clean | bool
